import {
  BarChart3,
  BookMarked,
  BookOpen,
  BriefcaseBusiness,
  Building,
  Building2,
  Bus,
  CalendarCheck,
  CalendarRange,
  ClipboardCheck,
  Compass,
  CreditCard,
  Database,
  GraduationCap,
  HeartHandshake,
  KeyRound,
  Layers,
  LayoutDashboard,
  LifeBuoy,
  Megaphone,
  MessageSquare,
  MonitorSmartphone,
  Network,
  PieChart,
  ScrollText,
  ServerCog,
  ShieldCheck,
  UserPlus,
  Users,
  Wallet,
  Warehouse,
} from "lucide-react";

/** Explicit map keeps the icon set tree-shakeable while data files stay plain strings. */
const ICONS = {
  BarChart3,
  BookMarked,
  BookOpen,
  BriefcaseBusiness,
  Building,
  Building2,
  Bus,
  CalendarCheck,
  CalendarRange,
  ClipboardCheck,
  Compass,
  CreditCard,
  Database,
  GraduationCap,
  HeartHandshake,
  KeyRound,
  Layers,
  LayoutDashboard,
  LifeBuoy,
  Megaphone,
  MessageSquare,
  MonitorSmartphone,
  Network,
  PieChart,
  ScrollText,
  ServerCog,
  ShieldCheck,
  UserPlus,
  Users,
  Wallet,
  Warehouse,
} as const;

export type ProductIconName = keyof typeof ICONS;

export function ProductIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICONS[name as ProductIconName] ?? LayoutDashboard;
  return <Icon className={className} aria-hidden="true" />;
}
